metadata:
  configurationMountPath: /opt/proxy_config
  httpContainer: example
  image: gcr.io/section-io/example-simple:1.0.0-k1
  logs:
    additional:
      - container: example
        name: error.log
        stream: stderr
    handler: example
    http:
      container: example
      stream: stdout
  metrics:
    path: /metrics
    port: 9000
  name: example-simple:1.0.0
spec:
  containers:
    - name: example
      resources:
        limits:
          memory: 20Mi
        requests:
          memory: 20Mi
hpa:
  apiVersion: autoscaling/v2beta1
  spec:
    minReplicas: 2
    maxReplicas: 4
    metrics:
    - type: Pods
      pods:
        metricName: pps20m
        targetAverageValue: 250
